#pragma once

enum JX_ANIMATION_PART
{
	JX_ANIMATION_PART_CHARACTER_CLOTH,
	JX_ANIMATION_PART_CHARACTER_HANDL,
	JX_ANIMATION_PART_CHARACTER_HANDR,
	JX_ANIMATION_PART_CHARACTER_HEAD,
	JX_ANIMATION_PART_CHARACTER_CAPE,
	JX_ANIMATION_PART_WEAPON_ONE,
	JX_ANIMATION_PART_WEAPON_TWO,
	JX_ANIMATION_PART_WEAPON_DUALL,
	JX_ANIMATION_PART_WEAPON_DUALR,
	JX_ANIMATION_PART_HORSE_HEAD,
	JX_ANIMATION_PART_HORSE_BACK,
	JX_ANIMATION_PART_HORSE_TAIL
};

#define JX_ANIMATION_PATH_CHARACTER_CLOTH_M	"character_male_cloth"
#define JX_ANIMATION_PATH_CHARACTER_CLOTH_F	"character_female_cloth"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_M	"character_male_handl"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_F	"character_female_handl"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_M	"character_male_handr"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_F	"character_female_handr"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_M	"character_male_head"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_F	"character_female_head"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_M	"character_male_cape"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_F	"character_female_cape"
#define JX_ANIMATION_PATH_WEAPON_ONE_M		"weapon_male_one"
#define JX_ANIMATION_PATH_WEAPON_ONE_F		"weapon_female_one"
#define JX_ANIMATION_PATH_WEAPON_TWO_M		"weapon_male_two"
#define JX_ANIMATION_PATH_WEAPON_TWO_F		"weapon_female_two"
#define JX_ANIMATION_PATH_WEAPON_DUALL_M		"weapon_male_duall"
#define JX_ANIMATION_PATH_WEAPON_DUALL_F		"weapon_female_duall"
#define JX_ANIMATION_PATH_WEAPON_DUALR_M		"weapon_male_dualr"
#define JX_ANIMATION_PATH_WEAPON_DUALR_F		"weapon_female_dualr"
#define JX_ANIMATION_PATH_RIDE_HEAD			"horse_head"
#define JX_ANIMATION_PATH_RIDE_BACK			"horse_back"
#define JX_ANIMATION_PATH_RIDE_TAIL			"horse_tail"

// F = free hand, O = one hand, T = two hand, D = dual hand
// C = critical
enum JX_ANIMATION_STATE
{
	JX_ANIMATION_STATE_ZEN = 0,
	JX_ANIMATION_STATE_IDLE_F,
	JX_ANIMATION_STATE_FIGHTIDLE_F,
	JX_ANIMATION_STATE_WALK_F,
	JX_ANIMATION_STATE_RUN_F,
	JX_ANIMATION_STATE_JUMP,
	JX_ANIMATION_STATE_ATK_FC,
	JX_ANIMATION_STATE_ATK_F,
	JX_ANIMATION_STATE_CAST_F,
	JX_ANIMATION_STATE_HURT_F,
	JX_ANIMATION_STATE_FALL_F,

	JX_ANIMATION_STATE_IDLE_O,
	JX_ANIMATION_STATE_FIGHTIDLE_O,
	JX_ANIMATION_STATE_WALK_O,
	JX_ANIMATION_STATE_RUN_O,
	JX_ANIMATION_STATE_ATK_OC,
	JX_ANIMATION_STATE_ATK_O,
	JX_ANIMATION_STATE_CAST_O,
	JX_ANIMATION_STATE_HURT_O,
	JX_ANIMATION_STATE_FALL_O,

	JX_ANIMATION_STATE_IDLE_T,
	JX_ANIMATION_STATE_FIGHTIDLE_T,
	JX_ANIMATION_STATE_WALK_T,
	JX_ANIMATION_STATE_RUN_T,
	JX_ANIMATION_STATE_ATK_TC,
	JX_ANIMATION_STATE_ATK_T,
	JX_ANIMATION_STATE_CAST_T,
	JX_ANIMATION_STATE_HURT_T,
	JX_ANIMATION_STATE_FALL_T,

	JX_ANIMATION_STATE_IDLE_D,
	JX_ANIMATION_STATE_FIGHTIDLE_D,
	JX_ANIMATION_STATE_WALK_D,
	JX_ANIMATION_STATE_RUN_D,
	JX_ANIMATION_STATE_ATK_DC,
	JX_ANIMATION_STATE_ATK_D,
	JX_ANIMATION_STATE_CAST_D,
	JX_ANIMATION_STATE_HURT_D,
	JX_ANIMATION_STATE_FALL_D,
	
	// RIDE
	JX_ANIMATION_STATE_RIDE_IDLE_F,
	JX_ANIMATION_STATE_RIDE_WALK_F,
	JX_ANIMATION_STATE_RIDE_RUN_F,
	JX_ANIMATION_STATE_RIDE_ATK_FC,
	JX_ANIMATION_STATE_RIDE_ATK_F,
	JX_ANIMATION_STATE_RIDE_CAST_F,
	JX_ANIMATION_STATE_RIDE_HURT_F,
	JX_ANIMATION_STATE_RIDE_FALL_F,
};

#define BYTE unsigned char

const BYTE JX_ANIMATION_STATE_TABLE[70][5] = {
	// CLOTH, ONEHAND_WEAPON, TWOHAND_WEAPON, DUAL_WEAPON, RIDE
	{1, 0, 0, 0, 0},//JX_ANIMATION_STATE_ATK_F
	{2, 1, 0, 0, 0},//JX_ANIMATION_STATE_ATK_OC
	{3, 2, 0, 0, 0},//JX_ANIMATION_STATE_ATK_O
	{4, 0, 1, 0, 0},//JX_ANIMATION_STATE_ATK_TC
	{5, 0, 2, 0, 0},//JX_ANIMATION_STATE_ATK_T
	{6, 0, 0, 1, 0},//JX_ANIMATION_STATE_ATK_DC
	{7, 0, 0, 2, 0},//JX_ANIMATION_STATE_ATK_D

	{8, 0, 0, 0, 0},//JX_ANIMATION_STATE_FALL_F
	{9, 3, 0, 0, 0},//JX_ANIMATION_STATE_FALL_O
	{10, 0, 3, 0, 0},//JX_ANIMATION_STATE_FALL_T
	{11, 0, 0, 3, 0},//JX_ANIMATION_STATE_FALL_D

	{19, 0, 0, 0, 0},//JX_ANIMATION_STATE_HURT_F
	{20, 11, 0, 0, 0},//JX_ANIMATION_STATE_HURT_O
	{21, 0, 11, 0, 0},//JX_ANIMATION_STATE_HURT_T
	{22, 0, 0, 11, 0},//JX_ANIMATION_STATE_HURT_D

	{23, 0, 0, 0, 0},//JX_ANIMATION_STATE_JUMP
	{24, 0, 0, 0, 0},//JX_ANIMATION_STATE_ATK_FC

	{25, 0, 0, 0, 0},//JX_ANIMATION_STATE_CAST_F
	{26, 12, 0, 0, 0},//JX_ANIMATION_STATE_CAST_O
	{27, 0, 12, 0, 0},//JX_ANIMATION_STATE_CAST_T
	{28, 0, 0, 12, 0},//JX_ANIMATION_STATE_CAST_D

	{30, 0, 0, 0, 0},//JX_ANIMATION_STATE_RUN_F
	{31, 14, 0, 0, 0},//JX_ANIMATION_STATE_RUN_O
	{32, 0, 14, 0, 0},//JX_ANIMATION_STATE_RUN_T
	{33, 0, 0, 14, 0},//JX_ANIMATION_STATE_RUN_D

	{34, 0, 0, 0, 0},//JX_ANIMATION_STATE_IDLE_F
	{35, 15, 0, 0, 0},//JX_ANIMATION_STATE_IDLE_O
	{35, 0, 15, 0, 0},//JX_ANIMATION_STATE_IDLE_T
	{35, 0, 0, 15, 0},//JX_ANIMATION_STATE_IDLE_D

	{36, 0, 0, 0, 0},//JX_ANIMATION_STATE_FIGHTIDLE_F
	{37, 17, 0, 0, 0},//JX_ANIMATION_STATE_FIGHTIDLE_O
	{38, 0, 17, 0, 0},//JX_ANIMATION_STATE_FIGHTIDLE_T
	{39, 0, 0, 17, 0},//JX_ANIMATION_STATE_FIGHTIDLE_D

	{40, 0, 0, 0, 0},//JX_ANIMATION_STATE_WALK_F
	{41, 18, 0, 0, 0},//JX_ANIMATION_STATE_WALK_O
	{42, 0, 18, 0, 0},//JX_ANIMATION_STATE_WALK_T
	{43, 0, 0, 18, 0},//JX_ANIMATION_STATE_WALK_D

	{44, 0, 0, 0, 0},//JX_ANIMATION_STATE_ZEN
	// RIDE
	{12, 0, 0, 0, 1},//JX_ANIMATION_STATE_RIDE_ATK_FC
	{12, 4, 0, 0, 1},//JX_ANIMATION_STATE_RIDE_ATK_OC
	{12, 0, 4, 0, 1},//JX_ANIMATION_STATE_RIDE_ATK_TC
	{12, 0, 0, 4, 1},//JX_ANIMATION_STATE_RIDE_ATK_DC

	{13, 0, 0, 0, 2},//JX_ANIMATION_STATE_RIDE_ATK_F
	{13, 4, 0, 0, 2},//JX_ANIMATION_STATE_RIDE_ATK_O
	{13, 0, 4, 0, 2},//JX_ANIMATION_STATE_RIDE_ATK_T
	{13, 0, 0, 4, 2},//JX_ANIMATION_STATE_RIDE_ATK_D

	{15, 0, 0, 0, 4},//JX_ANIMATION_STATE_RIDE_HURT_F
	{15, 7, 0, 0, 4},//JX_ANIMATION_STATE_RIDE_HURT_O
	{15, 0, 7, 0, 4},//JX_ANIMATION_STATE_RIDE_HURT_T
	{15, 0, 0, 7, 4},//JX_ANIMATION_STATE_RIDE_HURT_D

	{16, 0, 0, 0, 5},//JX_ANIMATION_STATE_RIDE_CAST_F
	{16, 8, 0, 0, 5},//JX_ANIMATION_STATE_RIDE_CAST_O
	{16, 0, 8, 0, 5},//JX_ANIMATION_STATE_RIDE_CAST_T
	{16, 0, 0, 8, 5},//JX_ANIMATION_STATE_RIDE_CAST_D

	{17, 0, 0, 0, 6},//JX_ANIMATION_STATE_RIDE_RUN_F
	{17, 9, 0, 0, 6},//JX_ANIMATION_STATE_RIDE_RUN_O
	{17, 0, 9, 0, 6},//JX_ANIMATION_STATE_RIDE_RUN_T
	{17, 0, 0, 9, 6},//JX_ANIMATION_STATE_RIDE_RUN_D

	{18, 0, 0, 0, 7},//JX_ANIMATION_STATE_RIDE_WALK_F
	{18, 10, 0, 0, 7},//JX_ANIMATION_STATE_RIDE_WALK_O
	{18, 0, 10, 0, 7},//JX_ANIMATION_STATE_RIDE_WALK_T
	{18, 0, 0, 10, 7},//JX_ANIMATION_STATE_RIDE_WALK_D

	{29, 0, 0, 0, 8},//JX_ANIMATION_STATE_RIDE_IDLE_F
	{29, 13, 0, 0, 8},//JX_ANIMATION_STATE_RIDE_IDLE_O
	{29, 0, 13, 0, 8},//JX_ANIMATION_STATE_RIDE_IDLE_T
	{29, 0, 0, 13, 8}//JX_ANIMATION_STATE_RIDE_IDLE_D
};
const unsigned char JX_ANIMATION_MALE_FRAME[70] = {
	18,//JX_ANIMATION_STATE_ATK_F
	16,//JX_ANIMATION_STATE_ATK_OC
	14,//JX_ANIMATION_STATE_ATK_O
	12,//JX_ANIMATION_STATE_ATK_TC
	12,//JX_ANIMATION_STATE_ATK_T
	16,//JX_ANIMATION_STATE_ATK_DC
	12,//JX_ANIMATION_STATE_ATK_D

	12,//JX_ANIMATION_STATE_FALL_F
	11,//JX_ANIMATION_STATE_FALL_O
	15,//JX_ANIMATION_STATE_FALL_T
	18,//JX_ANIMATION_STATE_FALL_D

	9,//JX_ANIMATION_STATE_HURT_F
	8,//JX_ANIMATION_STATE_HURT_O
	7,//JX_ANIMATION_STATE_HURT_T
	12,//JX_ANIMATION_STATE_HURT_D

	20,//JX_ANIMATION_STATE_JUMP
	16,//JX_ANIMATION_STATE_ATK_FC

	12,//JX_ANIMATION_STATE_CAST_F
	12,//JX_ANIMATION_STATE_CAST_O
	13,//JX_ANIMATION_STATE_CAST_T
	16,//JX_ANIMATION_STATE_CAST_D

	11,//JX_ANIMATION_STATE_RUN_F
	11,//JX_ANIMATION_STATE_RUN_O
	11,//JX_ANIMATION_STATE_RUN_T
	11,//JX_ANIMATION_STATE_RUN_D

	15,//JX_ANIMATION_STATE_IDLE_F
	15,//JX_ANIMATION_STATE_IDLE_O
	15,//JX_ANIMATION_STATE_IDLE_T
	15,//JX_ANIMATION_STATE_IDLE_D

	11,//JX_ANIMATION_STATE_FIGHTIDLE_F
	11,//JX_ANIMATION_STATE_FIGHTIDLE_O
	11,//JX_ANIMATION_STATE_FIGHTIDLE_T
	11,//JX_ANIMATION_STATE_FIGHTIDLE_D

	15,//JX_ANIMATION_STATE_WALK_F
	15,//JX_ANIMATION_STATE_WALK_O
	15,//JX_ANIMATION_STATE_WALK_T
	15,//JX_ANIMATION_STATE_WALK_D

	9,//JX_ANIMATION_STATE_ZEN
	// RIDE
	12,//JX_ANIMATION_STATE_RIDE_ATK_FC
	12,//JX_ANIMATION_STATE_RIDE_ATK_OC
	12,//JX_ANIMATION_STATE_RIDE_ATK_TC
	12,//JX_ANIMATION_STATE_RIDE_ATK_DC
	
	14,//JX_ANIMATION_STATE_RIDE_ATK_F
	14,//JX_ANIMATION_STATE_RIDE_ATK_O
	14,//JX_ANIMATION_STATE_RIDE_ATK_T
	14,//JX_ANIMATION_STATE_RIDE_ATK_D

	14,//JX_ANIMATION_STATE_RIDE_FALL_F
	14,//JX_ANIMATION_STATE_RIDE_FALL_O
	14,//JX_ANIMATION_STATE_RIDE_FALL_T
	14,//JX_ANIMATION_STATE_RIDE_FALL_D

	6,//JX_ANIMATION_STATE_RIDE_HURT_F
	6,//JX_ANIMATION_STATE_RIDE_HURT_O
	6,//JX_ANIMATION_STATE_RIDE_HURT_T
	6,//JX_ANIMATION_STATE_RIDE_HURT_D

	12,//JX_ANIMATION_STATE_RIDE_CAST_F
	12,//JX_ANIMATION_STATE_RIDE_CAST_O
	12,//JX_ANIMATION_STATE_RIDE_CAST_T
	12,//JX_ANIMATION_STATE_RIDE_CAST_D

	10,//JX_ANIMATION_STATE_RIDE_RUN_F
	10,//JX_ANIMATION_STATE_RIDE_RUN_O
	10,//JX_ANIMATION_STATE_RIDE_RUN_T
	10,//JX_ANIMATION_STATE_RIDE_RUN_D

	12,//JX_ANIMATION_STATE_RIDE_WALK_F
	12,//JX_ANIMATION_STATE_RIDE_WALK_O
	12,//JX_ANIMATION_STATE_RIDE_WALK_T
	12,//JX_ANIMATION_STATE_RIDE_WALK_D

	14,//JX_ANIMATION_STATE_RIDE_IDLE_F
	14,//JX_ANIMATION_STATE_RIDE_IDLE_O
	14,//JX_ANIMATION_STATE_RIDE_IDLE_T
	14//JX_ANIMATION_STATE_RIDE_IDLE_D
};
const BYTE JX_ANIMATION_FEMALE_FRAME[70] = {
	12,//JX_ANIMATION_STATE_ATK_F
	13,//JX_ANIMATION_STATE_ATK_OC
	13,//JX_ANIMATION_STATE_ATK_O
	13,//JX_ANIMATION_STATE_ATK_TC
	12,//JX_ANIMATION_STATE_ATK_T
	16,//JX_ANIMATION_STATE_ATK_DC
	12,//JX_ANIMATION_STATE_ATK_D

	13,//JX_ANIMATION_STATE_FALL_F
	15,//JX_ANIMATION_STATE_FALL_O
	10,//JX_ANIMATION_STATE_FALL_T
	10,//JX_ANIMATION_STATE_FALL_D

	8,//JX_ANIMATION_STATE_HURT_F
	8,//JX_ANIMATION_STATE_HURT_O
	6,//JX_ANIMATION_STATE_HURT_T
	6,//JX_ANIMATION_STATE_HURT_D

	14,//JX_ANIMATION_STATE_JUMP
	12,//JX_ANIMATION_STATE_ATK_FC

	12,//JX_ANIMATION_STATE_CAST_F
	10,//JX_ANIMATION_STATE_CAST_O
	12,//JX_ANIMATION_STATE_CAST_T
	10,//JX_ANIMATION_STATE_CAST_D

	12,//JX_ANIMATION_STATE_RUN_F
	12,//JX_ANIMATION_STATE_RUN_O
	12,//JX_ANIMATION_STATE_RUN_T
	12,//JX_ANIMATION_STATE_RUN_D

	10,//JX_ANIMATION_STATE_IDLE_F
	8,//JX_ANIMATION_STATE_IDLE_O
	8,//JX_ANIMATION_STATE_IDLE_T
	8,//JX_ANIMATION_STATE_IDLE_D

	8,//JX_ANIMATION_STATE_FIGHTIDLE_F
	12,//JX_ANIMATION_STATE_FIGHTIDLE_O
	8,//JX_ANIMATION_STATE_FIGHTIDLE_T
	8,//JX_ANIMATION_STATE_FIGHTIDLE_D

	12,//JX_ANIMATION_STATE_WALK_F
	12,//JX_ANIMATION_STATE_WALK_O
	12,//JX_ANIMATION_STATE_WALK_T
	12,//JX_ANIMATION_STATE_WALK_D

	12,//JX_ANIMATION_STATE_ZEN
	// RIDE
	12,//JX_ANIMATION_STATE_RIDE_ATK_FC
	12,//JX_ANIMATION_STATE_RIDE_ATK_OC
	12,//JX_ANIMATION_STATE_RIDE_ATK_TC
	12,//JX_ANIMATION_STATE_RIDE_ATK_DC
	
	14,//JX_ANIMATION_STATE_RIDE_ATK_F
	14,//JX_ANIMATION_STATE_RIDE_ATK_O
	14,//JX_ANIMATION_STATE_RIDE_ATK_T
	14,//JX_ANIMATION_STATE_RIDE_ATK_D

	14,//JX_ANIMATION_STATE_RIDE_FALL_F
	14,//JX_ANIMATION_STATE_RIDE_FALL_O
	14,//JX_ANIMATION_STATE_RIDE_FALL_T
	14,//JX_ANIMATION_STATE_RIDE_FALL_D

	6,//JX_ANIMATION_STATE_RIDE_HURT_F
	6,//JX_ANIMATION_STATE_RIDE_HURT_O
	6,//JX_ANIMATION_STATE_RIDE_HURT_T
	6,//JX_ANIMATION_STATE_RIDE_HURT_D

	12,//JX_ANIMATION_STATE_RIDE_CAST_F
	12,//JX_ANIMATION_STATE_RIDE_CAST_O
	12,//JX_ANIMATION_STATE_RIDE_CAST_T
	12,//JX_ANIMATION_STATE_RIDE_CAST_D

	10,//JX_ANIMATION_STATE_RIDE_RUN_F
	10,//JX_ANIMATION_STATE_RIDE_RUN_O
	10,//JX_ANIMATION_STATE_RIDE_RUN_T
	10,//JX_ANIMATION_STATE_RIDE_RUN_D

	12,//JX_ANIMATION_STATE_RIDE_WALK_F
	12,//JX_ANIMATION_STATE_RIDE_WALK_O
	12,//JX_ANIMATION_STATE_RIDE_WALK_T
	12,//JX_ANIMATION_STATE_RIDE_WALK_D

	14,//JX_ANIMATION_STATE_RIDE_IDLE_F
	14,//JX_ANIMATION_STATE_RIDE_IDLE_O
	14,//JX_ANIMATION_STATE_RIDE_IDLE_T
	14//JX_ANIMATION_STATE_RIDE_IDLE_D
};
#undef BYTE