#pragma once

#define JX_ANIMATION_PATH_CHARACTER_CLOTH_M		"character_cloth_male"
#define JX_ANIMATION_PATH_CHARACTER_CLOTH_F		"character_cloth_female"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_M		"character_handl_male"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_F		"character_handl_female"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_M		"character_handr_male"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_F		"character_handr_female"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_M		"character_head_male"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_F		"character_head_female"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_M		"character_cape_male"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_F		"character_cape_female"
#define JX_ANIMATION_PATH_WEAPON_LIGHT_M		"weapon_light_male"
#define JX_ANIMATION_PATH_WEAPON_LIGHT_F		"weapon_light_female"
#define JX_ANIMATION_PATH_WEAPON_HEAVY_M		"weapon_heavy_male"
#define JX_ANIMATION_PATH_WEAPON_HEAVY_F		"weapon_heavy_female"
#define JX_ANIMATION_PATH_WEAPON_DUALL_M		"weapon_duall_male"
#define JX_ANIMATION_PATH_WEAPON_DUALL_F		"weapon_duall_female"
#define JX_ANIMATION_PATH_WEAPON_DUALR_M		"weapon_dualr_male"
#define JX_ANIMATION_PATH_WEAPON_DUALR_F		"weapon_dualr_female"
#define JX_ANIMATION_PATH_RIDE_HEAD				"horse_head"
#define JX_ANIMATION_PATH_RIDE_BACK				"horse_back"
#define JX_ANIMATION_PATH_RIDE_TAIL				"horse_tail"

// F = free hand, O = one hand, T = two hand, D = dual hand
// C = critical
enum JX_ANIMATION_STATE
{
	JX_ANIMATION_STATE_ZEN				= 0 | (0<<4) | (0<<6),

	JX_ANIMATION_STATE_IDLE_FREE		= 1 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_READY_FREE		= 2 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_WALK_FREE		= 3 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_RUN_FREE			= 4 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_JUMP				= 5 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_ATKCRIT_FREE		= 6 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_ATK_FREE			= 7 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_CAST_FREE		= 8 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_HURT_FREE		= 9 | (0<<4) | (0<<6),
	JX_ANIMATION_STATE_FALL_FREE		= 10| (0<<4) | (0<<6),

	JX_ANIMATION_STATE_IDLE_LIGHT		= 1 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_READY_LIGHT		= 2 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_WALK_LIGHT		= 3 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_RUN_LIGHT		= 4 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_ATKCRIT_LIGHT	= 6 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_ATK_LIGHT		= 7 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_CAST_LIGHT		= 8 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_HURT_LIGHT		= 9 | (1<<4) | (0<<6),
	JX_ANIMATION_STATE_FALL_LIGHT		= 10| (1<<4) | (0<<6),

	JX_ANIMATION_STATE_IDLE_HEAVY		= 1 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_READY_HEAVY		= 2 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_WALK_HEAVY		= 3 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_RUN_HEAVY		= 4 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_ATKCRIT_HEAVY	= 6 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_ATK_HEAVY		= 7 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_CAST_HEAVY		= 8 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_HURT_HEAVY		= 9 | (2<<4) | (0<<6),
	JX_ANIMATION_STATE_FALL_HEAVY		= 10| (2<<4) | (0<<6),

	JX_ANIMATION_STATE_IDLE_DUAL		= 1 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_READY_DUAL		= 2 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_WALK_DUAL		= 3 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_RUN_DUAL			= 4 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_ATKCRIT_DUAL		= 6 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_ATK_DUAL			= 7 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_CAST_DUAL		= 8 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_HURT_DUAL		= 9 | (3<<4) | (0<<6),
	JX_ANIMATION_STATE_FALL_DUAL		= 10| (3<<4) | (0<<6),
	
	// RIDE
	JX_ANIMATION_STATE_RIDE_IDLE		= 1 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_WALK		= 3 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_RUN			= 4 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_ATKCRIT		= 6 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_ATK			= 7 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_CAST		= 8 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_HURT		= 9 | (0<<4) | (1<<6),
	JX_ANIMATION_STATE_RIDE_FALL		= 10| (0<<4) | (1<<6),
};

const unsigned char JX_ANIMATION_MALE_FRAME[75] = {
	9,//JX_ANIMATION_STATE_ZEN

	15,//JX_ANIMATION_STATE_IDLE_FREE
	11,//JX_ANIMATION_STATE_READY_FREE
	15,//JX_ANIMATION_STATE_WALK_FREE
	11,//JX_ANIMATION_STATE_RUN_FREE
	20,//JX_ANIMATION_STATE_JUMP
	16,//JX_ANIMATION_STATE_ATKCRIT_FREE
	18,//JX_ANIMATION_STATE_ATK_FREE
	12,//JX_ANIMATION_STATE_CAST_FREE
	9,//JX_ANIMATION_STATE_HURT_FREE
	12,//JX_ANIMATION_STATE_FALL_FREE
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_LIGHT
	11,//JX_ANIMATION_STATE_READY_LIGHT
	15,//JX_ANIMATION_STATE_WALK_LIGHT
	11,//JX_ANIMATION_STATE_RUN_LIGHT
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_LIGHT
	14,//JX_ANIMATION_STATE_ATK_LIGHT
	12,//JX_ANIMATION_STATE_CAST_LIGHT
	8,//JX_ANIMATION_STATE_HURT_LIGHT
	11,//JX_ANIMATION_STATE_FALL_LIGHT
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_HEAVY
	11,//JX_ANIMATION_STATE_READY_HEAVY
	15,//JX_ANIMATION_STATE_WALK_HEAVY
	11,//JX_ANIMATION_STATE_RUN_HEAVY
	0,
	12,//JX_ANIMATION_STATE_ATKCRIT_HEAVY
	12,//JX_ANIMATION_STATE_ATK_HEAVY
	13,//JX_ANIMATION_STATE_CAST_HEAVY
	7,//JX_ANIMATION_STATE_HURT_HEAVY
	15,//JX_ANIMATION_STATE_FALL_HEAVY
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_DUAL
	11,//JX_ANIMATION_STATE_READY_DUAL
	15,//JX_ANIMATION_STATE_WALK_DUAL
	11,//JX_ANIMATION_STATE_RUN_DUAL
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_DUAL
	12,//JX_ANIMATION_STATE_ATK_DUAL
	16,//JX_ANIMATION_STATE_CAST_DUAL
	12,//JX_ANIMATION_STATE_HURT_DUAL
	18,//JX_ANIMATION_STATE_FALL_DUAL
	0,
	0,
	0,
	0,
	0,
	0,
	// RIDE
	14,//JX_ANIMATION_STATE_RIDE_IDLE_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_WALK_FREE
	10,//JX_ANIMATION_STATE_RIDE_RUN_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_ATKCRIT_FREE
	14,//JX_ANIMATION_STATE_RIDE_ATK_FREE
	12,//JX_ANIMATION_STATE_RIDE_CAST_FREE
	6,//JX_ANIMATION_STATE_RIDE_HURT_FREE
	14,//JX_ANIMATION_STATE_RIDE_FALL_FREE
};
const unsigned char JX_ANIMATION_FEMALE_FRAME[75] = {
	12,//JX_ANIMATION_STATE_ZEN
	10,//JX_ANIMATION_STATE_IDLE_FREE
	8,//JX_ANIMATION_STATE_READY_FREE
	12,//JX_ANIMATION_STATE_WALK_FREE
	12,//JX_ANIMATION_STATE_RUN_FREE
	14,//JX_ANIMATION_STATE_JUMP
	12,//JX_ANIMATION_STATE_ATKCRIT_FREE
	12,//JX_ANIMATION_STATE_ATK_FREE
	12,//JX_ANIMATION_STATE_CAST_FREE
	8,//JX_ANIMATION_STATE_HURT_FREE
	13,//JX_ANIMATION_STATE_FALL_FREE
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_LIGHT
	12,//JX_ANIMATION_STATE_READY_LIGHT
	12,//JX_ANIMATION_STATE_WALK_LIGHT
	12,//JX_ANIMATION_STATE_RUN_LIGHT
	0,
	13,//JX_ANIMATION_STATE_ATKCRIT_LIGHT
	13,//JX_ANIMATION_STATE_ATK_LIGHT
	10,//JX_ANIMATION_STATE_CAST_LIGHT
	8,//JX_ANIMATION_STATE_HURT_LIGHT
	15,//JX_ANIMATION_STATE_FALL_LIGHT
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_HEAVY
	8,//JX_ANIMATION_STATE_READY_HEAVY
	12,//JX_ANIMATION_STATE_WALK_HEAVY
	12,//JX_ANIMATION_STATE_RUN_HEAVY
	0,
	13,//JX_ANIMATION_STATE_ATKCRIT_HEAVY
	12,//JX_ANIMATION_STATE_ATK_HEAVY
	12,//JX_ANIMATION_STATE_CAST_HEAVY
	6,//JX_ANIMATION_STATE_HURT_HEAVY
	10,//JX_ANIMATION_STATE_FALL_HEAVY
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_DUAL
	8,//JX_ANIMATION_STATE_READY_DUAL
	12,//JX_ANIMATION_STATE_WALK_DUAL
	12,//JX_ANIMATION_STATE_RUN_DUAL
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_DUAL
	12,//JX_ANIMATION_STATE_ATK_DUAL
	10,//JX_ANIMATION_STATE_CAST_DUAL
	6,//JX_ANIMATION_STATE_HURT_DUAL
	10,//JX_ANIMATION_STATE_FALL_DUAL
	0,
	0,
	0,
	0,
	0,
	0,
	// RIDE
	14,//JX_ANIMATION_STATE_RIDE_IDLE_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_WALK_FREE
	10,//JX_ANIMATION_STATE_RIDE_RUN_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_ATK_FREEC
	14,//JX_ANIMATION_STATE_RIDE_ATK_FREE
	12,//JX_ANIMATION_STATE_RIDE_CAST_FREE
	6,//JX_ANIMATION_STATE_RIDE_HURT_FREE
	14,//JX_ANIMATION_STATE_RIDE_FALL_FREE
};