#pragma once

enum RIG_ENGINE_PART
{
	RIG_ENGINE_PART_CHARACTER_CLOTH,
	RIG_ENGINE_PART_CHARACTER_HANDL,
	RIG_ENGINE_PART_CHARACTER_HANDR,
	RIG_ENGINE_PART_CHARACTER_HEAD,
	RIG_ENGINE_PART_CHARACTER_CAPE,
	RIG_ENGINE_PART_WEAPON_ONE,
	RIG_ENGINE_PART_WEAPON_TWO,
	RIG_ENGINE_PART_WEAPON_DUALL,
	RIG_ENGINE_PART_WEAPON_DUALR,
	RIG_ENGINE_PART_HORSE_HEAD,
	RIG_ENGINE_PART_HORSE_BACK,
	RIG_ENGINE_PART_HORSE_TAIL
};

#define RIG_ENGINE_PATH_CHARACTER_CLOTH_M	"character_male_cloth"
#define RIG_ENGINE_PATH_CHARACTER_CLOTH_F	"character_female_cloth"
#define RIG_ENGINE_PATH_CHARACTER_HANDL_M	"character_male_handl"
#define RIG_ENGINE_PATH_CHARACTER_HANDL_F	"character_female_handl"
#define RIG_ENGINE_PATH_CHARACTER_HANDR_M	"character_male_handr"
#define RIG_ENGINE_PATH_CHARACTER_HANDR_F	"character_female_handr"
#define RIG_ENGINE_PATH_CHARACTER_HEAD_M	"character_male_head"
#define RIG_ENGINE_PATH_CHARACTER_HEAD_F	"character_female_head"
#define RIG_ENGINE_PATH_CHARACTER_CAPE_M	"character_male_cape"
#define RIG_ENGINE_PATH_CHARACTER_CAPE_F	"character_female_cape"
#define RIG_ENGINE_PATH_WEAPON_ONE_M		"weapon_male_one"
#define RIG_ENGINE_PATH_WEAPON_ONE_F		"weapon_female_one"
#define RIG_ENGINE_PATH_WEAPON_TWO_M		"weapon_male_two"
#define RIG_ENGINE_PATH_WEAPON_TWO_F		"weapon_female_two"
#define RIG_ENGINE_PATH_WEAPON_DUALL_M		"weapon_male_duall"
#define RIG_ENGINE_PATH_WEAPON_DUALL_F		"weapon_female_duall"
#define RIG_ENGINE_PATH_WEAPON_DUALR_M		"weapon_male_dualr"
#define RIG_ENGINE_PATH_WEAPON_DUALR_F		"weapon_female_dualr"
#define RIG_ENGINE_PATH_HORSE_HEAD			"horse_head"
#define RIG_ENGINE_PATH_HORSE_BACK			"horse_back"
#define RIG_ENGINE_PATH_HORSE_TAIL			"horse_tail"

// F = free hand, O = one hand, T = two hand, D = dual hand
// C = critical
enum RIG_ENGINE_STATE
{
	RIG_ENGINE_STATE_ATK_F,
	RIG_ENGINE_STATE_ATK_OC,
	RIG_ENGINE_STATE_ATK_O,
	RIG_ENGINE_STATE_ATK_TC,
	RIG_ENGINE_STATE_ATK_T,
	RIG_ENGINE_STATE_ATK_DC,
	RIG_ENGINE_STATE_ATK_D,

	RIG_ENGINE_STATE_FALL_F,
	RIG_ENGINE_STATE_FALL_O,
	RIG_ENGINE_STATE_FALL_T,
	RIG_ENGINE_STATE_FALL_D,

	RIG_ENGINE_STATE_HURT_F,
	RIG_ENGINE_STATE_HURT_O,
	RIG_ENGINE_STATE_HURT_T,
	RIG_ENGINE_STATE_HURT_D,

	RIG_ENGINE_STATE_JUMP,
	RIG_ENGINE_STATE_ATK_FC,

	RIG_ENGINE_STATE_CAST_F,
	RIG_ENGINE_STATE_CAST_O,
	RIG_ENGINE_STATE_CAST_T,
	RIG_ENGINE_STATE_CAST_D,

	RIG_ENGINE_STATE_RUN_F,
	RIG_ENGINE_STATE_RUN_O,
	RIG_ENGINE_STATE_RUN_T,
	RIG_ENGINE_STATE_RUN_D,

	RIG_ENGINE_STATE_IDLE_F,
	RIG_ENGINE_STATE_IDLE_O,
	RIG_ENGINE_STATE_IDLE_T,
	RIG_ENGINE_STATE_IDLE_D,

	RIG_ENGINE_STATE_FIGHTIDLE_F,
	RIG_ENGINE_STATE_FIGHTIDLE_O,
	RIG_ENGINE_STATE_FIGHTIDLE_T,
	RIG_ENGINE_STATE_FIGHTIDLE_D,

	RIG_ENGINE_STATE_WALK_F,
	RIG_ENGINE_STATE_WALK_O,
	RIG_ENGINE_STATE_WALK_T,
	RIG_ENGINE_STATE_WALK_D,

	RIG_ENGINE_STATE_ZEN,
	// HORSE
	RIG_ENGINE_STATE_HORSE_ATK_FC,
	RIG_ENGINE_STATE_HORSE_ATK_OC,
	RIG_ENGINE_STATE_HORSE_ATK_TC,
	RIG_ENGINE_STATE_HORSE_ATK_DC,

	RIG_ENGINE_STATE_HORSE_ATK_F,
	RIG_ENGINE_STATE_HORSE_ATK_O,
	RIG_ENGINE_STATE_HORSE_ATK_T,
	RIG_ENGINE_STATE_HORSE_ATK_D,

	RIG_ENGINE_STATE_HORSE_FALL_F,
	RIG_ENGINE_STATE_HORSE_FALL_O,
	RIG_ENGINE_STATE_HORSE_FALL_T,
	RIG_ENGINE_STATE_HORSE_FALL_D,

	RIG_ENGINE_STATE_HORSE_HURT_F,
	RIG_ENGINE_STATE_HORSE_HURT_O,
	RIG_ENGINE_STATE_HORSE_HURT_T,
	RIG_ENGINE_STATE_HORSE_HURT_D,

	RIG_ENGINE_STATE_HORSE_CAST_F,
	RIG_ENGINE_STATE_HORSE_CAST_O,
	RIG_ENGINE_STATE_HORSE_CAST_T,
	RIG_ENGINE_STATE_HORSE_CAST_D,

	RIG_ENGINE_STATE_HORSE_RUN_F,
	RIG_ENGINE_STATE_HORSE_RUN_O,
	RIG_ENGINE_STATE_HORSE_RUN_T,
	RIG_ENGINE_STATE_HORSE_RUN_D,

	RIG_ENGINE_STATE_HORSE_WALK_F,
	RIG_ENGINE_STATE_HORSE_WALK_O,
	RIG_ENGINE_STATE_HORSE_WALK_T,
	RIG_ENGINE_STATE_HORSE_WALK_D,

	RIG_ENGINE_STATE_HORSE_IDLE_F,
	RIG_ENGINE_STATE_HORSE_IDLE_O,
	RIG_ENGINE_STATE_HORSE_IDLE_T,
	RIG_ENGINE_STATE_HORSE_IDLE_D
};

const unsigned char RIG_ENGINE_STATE_TABLE[70][5] = {
	// CLOTH, ONEHAND_WEAPON, TWOHAND_WEAPON, DUAL_WEAPON, HORSE
	{1, 0, 0, 0, 0},//RIG_ENGINE_STATE_ATK_F
	{2, 1, 0, 0, 0},//RIG_ENGINE_STATE_ATK_OC
	{3, 2, 0, 0, 0},//RIG_ENGINE_STATE_ATK_O
	{4, 0, 1, 0, 0},//RIG_ENGINE_STATE_ATK_TC
	{5, 0, 2, 0, 0},//RIG_ENGINE_STATE_ATK_T
	{6, 0, 0, 1, 0},//RIG_ENGINE_STATE_ATK_DC
	{7, 0, 0, 2, 0},//RIG_ENGINE_STATE_ATK_D

	{8, 0, 0, 0, 0},//RIG_ENGINE_STATE_FALL_F
	{9, 3, 0, 0, 0},//RIG_ENGINE_STATE_FALL_O
	{10, 0, 3, 0, 0},//RIG_ENGINE_STATE_FALL_T
	{11, 0, 0, 3, 0},//RIG_ENGINE_STATE_FALL_D

	{19, 0, 0, 0, 0},//RIG_ENGINE_STATE_HURT_F
	{20, 11, 0, 0, 0},//RIG_ENGINE_STATE_HURT_O
	{21, 0, 11, 0, 0},//RIG_ENGINE_STATE_HURT_T
	{22, 0, 0, 11, 0},//RIG_ENGINE_STATE_HURT_D

	{23, 0, 0, 0, 0},//RIG_ENGINE_STATE_JUMP
	{24, 0, 0, 0, 0},//RIG_ENGINE_STATE_ATK_FC

	{25, 0, 0, 0, 0},//RIG_ENGINE_STATE_CAST_F
	{26, 12, 0, 0, 0},//RIG_ENGINE_STATE_CAST_O
	{27, 0, 12, 0, 0},//RIG_ENGINE_STATE_CAST_T
	{28, 0, 0, 12, 0},//RIG_ENGINE_STATE_CAST_D

	{30, 0, 0, 0, 0},//RIG_ENGINE_STATE_RUN_F
	{31, 14, 0, 0, 0},//RIG_ENGINE_STATE_RUN_O
	{32, 0, 14, 0, 0},//RIG_ENGINE_STATE_RUN_T
	{33, 0, 0, 14, 0},//RIG_ENGINE_STATE_RUN_D

	{34, 0, 0, 0, 0},//RIG_ENGINE_STATE_IDLE_F
	{35, 15, 0, 0, 0},//RIG_ENGINE_STATE_IDLE_O
	{35, 0, 15, 0, 0},//RIG_ENGINE_STATE_IDLE_T
	{35, 0, 0, 15, 0},//RIG_ENGINE_STATE_IDLE_D

	{36, 0, 0, 0, 0},//RIG_ENGINE_STATE_FIGHTIDLE_F
	{37, 17, 0, 0, 0},//RIG_ENGINE_STATE_FIGHTIDLE_O
	{38, 0, 17, 0, 0},//RIG_ENGINE_STATE_FIGHTIDLE_T
	{39, 0, 0, 17, 0},//RIG_ENGINE_STATE_FIGHTIDLE_D

	{40, 0, 0, 0, 0},//RIG_ENGINE_STATE_WALK_F
	{41, 18, 0, 0, 0},//RIG_ENGINE_STATE_WALK_O
	{42, 0, 18, 0, 0},//RIG_ENGINE_STATE_WALK_T
	{43, 0, 0, 18, 0},//RIG_ENGINE_STATE_WALK_D

	{44, 0, 0, 0, 0},//RIG_ENGINE_STATE_ZEN
	// HORSE
	{12, 0, 0, 0, 1},//RIG_ENGINE_STATE_HORSE_ATK_FC
	{12, 4, 0, 0, 1},//RIG_ENGINE_STATE_HORSE_ATK_OC
	{12, 0, 4, 0, 1},//RIG_ENGINE_STATE_HORSE_ATK_TC
	{12, 0, 0, 4, 1},//RIG_ENGINE_STATE_HORSE_ATK_DC

	{13, 0, 0, 0, 2},//RIG_ENGINE_STATE_HORSE_ATK_F
	{13, 4, 0, 0, 2},//RIG_ENGINE_STATE_HORSE_ATK_O
	{13, 0, 4, 0, 2},//RIG_ENGINE_STATE_HORSE_ATK_T
	{13, 0, 0, 4, 2},//RIG_ENGINE_STATE_HORSE_ATK_D

	{15, 0, 0, 0, 4},//RIG_ENGINE_STATE_HORSE_HURT_F
	{15, 7, 0, 0, 4},//RIG_ENGINE_STATE_HORSE_HURT_O
	{15, 0, 7, 0, 4},//RIG_ENGINE_STATE_HORSE_HURT_T
	{15, 0, 0, 7, 4},//RIG_ENGINE_STATE_HORSE_HURT_D

	{16, 0, 0, 0, 5},//RIG_ENGINE_STATE_HORSE_CAST_F
	{16, 8, 0, 0, 5},//RIG_ENGINE_STATE_HORSE_CAST_O
	{16, 0, 8, 0, 5},//RIG_ENGINE_STATE_HORSE_CAST_T
	{16, 0, 0, 8, 5},//RIG_ENGINE_STATE_HORSE_CAST_D

	{17, 0, 0, 0, 6},//RIG_ENGINE_STATE_HORSE_RUN_F
	{17, 9, 0, 0, 6},//RIG_ENGINE_STATE_HORSE_RUN_O
	{17, 0, 9, 0, 6},//RIG_ENGINE_STATE_HORSE_RUN_T
	{17, 0, 0, 9, 6},//RIG_ENGINE_STATE_HORSE_RUN_D

	{18, 0, 0, 0, 7},//RIG_ENGINE_STATE_HORSE_WALK_F
	{18, 10, 0, 0, 7},//RIG_ENGINE_STATE_HORSE_WALK_O
	{18, 0, 10, 0, 7},//RIG_ENGINE_STATE_HORSE_WALK_T
	{18, 0, 0, 10, 7},//RIG_ENGINE_STATE_HORSE_WALK_D

	{29, 0, 0, 0, 8},//RIG_ENGINE_STATE_HORSE_IDLE_F
	{29, 13, 0, 0, 8},//RIG_ENGINE_STATE_HORSE_IDLE_O
	{29, 0, 13, 0, 8},//RIG_ENGINE_STATE_HORSE_IDLE_T
	{29, 0, 0, 13, 8}//RIG_ENGINE_STATE_HORSE_IDLE_D
};
const unsigned char RIG_ENGINE_MALE_FRAME[70] = {
	18,//RIG_ENGINE_STATE_ATK_F
	16,//RIG_ENGINE_STATE_ATK_OC
	14,//RIG_ENGINE_STATE_ATK_O
	12,//RIG_ENGINE_STATE_ATK_TC
	12,//RIG_ENGINE_STATE_ATK_T
	16,//RIG_ENGINE_STATE_ATK_DC
	12,//RIG_ENGINE_STATE_ATK_D

	12,//RIG_ENGINE_STATE_FALL_F
	11,//RIG_ENGINE_STATE_FALL_O
	15,//RIG_ENGINE_STATE_FALL_T
	18,//RIG_ENGINE_STATE_FALL_D

	9,//RIG_ENGINE_STATE_HURT_F
	8,//RIG_ENGINE_STATE_HURT_O
	7,//RIG_ENGINE_STATE_HURT_T
	12,//RIG_ENGINE_STATE_HURT_D

	20,//RIG_ENGINE_STATE_JUMP
	16,//RIG_ENGINE_STATE_ATK_FC

	12,//RIG_ENGINE_STATE_CAST_F
	12,//RIG_ENGINE_STATE_CAST_O
	13,//RIG_ENGINE_STATE_CAST_T
	16,//RIG_ENGINE_STATE_CAST_D

	11,//RIG_ENGINE_STATE_RUN_F
	11,//RIG_ENGINE_STATE_RUN_O
	11,//RIG_ENGINE_STATE_RUN_T
	11,//RIG_ENGINE_STATE_RUN_D

	15,//RIG_ENGINE_STATE_IDLE_F
	15,//RIG_ENGINE_STATE_IDLE_O
	15,//RIG_ENGINE_STATE_IDLE_T
	15,//RIG_ENGINE_STATE_IDLE_D

	11,//RIG_ENGINE_STATE_FIGHTIDLE_F
	11,//RIG_ENGINE_STATE_FIGHTIDLE_O
	11,//RIG_ENGINE_STATE_FIGHTIDLE_T
	11,//RIG_ENGINE_STATE_FIGHTIDLE_D

	15,//RIG_ENGINE_STATE_WALK_F
	15,//RIG_ENGINE_STATE_WALK_O
	15,//RIG_ENGINE_STATE_WALK_T
	15,//RIG_ENGINE_STATE_WALK_D

	9,//RIG_ENGINE_STATE_ZEN
	// HORSE
	12,//RIG_ENGINE_STATE_HORSE_ATK_FC
	12,//RIG_ENGINE_STATE_HORSE_ATK_OC
	12,//RIG_ENGINE_STATE_HORSE_ATK_TC
	12,//RIG_ENGINE_STATE_HORSE_ATK_DC
	
	14,//RIG_ENGINE_STATE_HORSE_ATK_F
	14,//RIG_ENGINE_STATE_HORSE_ATK_O
	14,//RIG_ENGINE_STATE_HORSE_ATK_T
	14,//RIG_ENGINE_STATE_HORSE_ATK_D

	6,//RIG_ENGINE_STATE_HORSE_HURT_F
	6,//RIG_ENGINE_STATE_HORSE_HURT_O
	6,//RIG_ENGINE_STATE_HORSE_HURT_T
	6,//RIG_ENGINE_STATE_HORSE_HURT_D

	12,//RIG_ENGINE_STATE_HORSE_CAST_F
	12,//RIG_ENGINE_STATE_HORSE_CAST_O
	12,//RIG_ENGINE_STATE_HORSE_CAST_T
	12,//RIG_ENGINE_STATE_HORSE_CAST_D

	10,//RIG_ENGINE_STATE_HORSE_RUN_F
	10,//RIG_ENGINE_STATE_HORSE_RUN_O
	10,//RIG_ENGINE_STATE_HORSE_RUN_T
	10,//RIG_ENGINE_STATE_HORSE_RUN_D

	12,//RIG_ENGINE_STATE_HORSE_WALK_F
	12,//RIG_ENGINE_STATE_HORSE_WALK_O
	12,//RIG_ENGINE_STATE_HORSE_WALK_T
	12,//RIG_ENGINE_STATE_HORSE_WALK_D

	14,//RIG_ENGINE_STATE_HORSE_IDLE_F
	14,//RIG_ENGINE_STATE_HORSE_IDLE_O
	14,//RIG_ENGINE_STATE_HORSE_IDLE_T
	14//RIG_ENGINE_STATE_HORSE_IDLE_D
};
const unsigned char RIG_ENGINE_FEMALE_FRAME[70] = {
	12,//RIG_ENGINE_STATE_ATK_F
	13,//RIG_ENGINE_STATE_ATK_OC
	13,//RIG_ENGINE_STATE_ATK_O
	13,//RIG_ENGINE_STATE_ATK_TC
	12,//RIG_ENGINE_STATE_ATK_T
	16,//RIG_ENGINE_STATE_ATK_DC
	12,//RIG_ENGINE_STATE_ATK_D

	13,//RIG_ENGINE_STATE_FALL_F
	15,//RIG_ENGINE_STATE_FALL_O
	10,//RIG_ENGINE_STATE_FALL_T
	10,//RIG_ENGINE_STATE_FALL_D

	8,//RIG_ENGINE_STATE_HURT_F
	8,//RIG_ENGINE_STATE_HURT_O
	6,//RIG_ENGINE_STATE_HURT_T
	6,//RIG_ENGINE_STATE_HURT_D

	14,//RIG_ENGINE_STATE_JUMP
	12,//RIG_ENGINE_STATE_ATK_FC

	12,//RIG_ENGINE_STATE_CAST_F
	10,//RIG_ENGINE_STATE_CAST_O
	12,//RIG_ENGINE_STATE_CAST_T
	10,//RIG_ENGINE_STATE_CAST_D

	12,//RIG_ENGINE_STATE_RUN_F
	12,//RIG_ENGINE_STATE_RUN_O
	12,//RIG_ENGINE_STATE_RUN_T
	12,//RIG_ENGINE_STATE_RUN_D

	10,//RIG_ENGINE_STATE_IDLE_F
	8,//RIG_ENGINE_STATE_IDLE_O
	8,//RIG_ENGINE_STATE_IDLE_T
	8,//RIG_ENGINE_STATE_IDLE_D

	8,//RIG_ENGINE_STATE_FIGHTIDLE_F
	12,//RIG_ENGINE_STATE_FIGHTIDLE_O
	8,//RIG_ENGINE_STATE_FIGHTIDLE_T
	8,//RIG_ENGINE_STATE_FIGHTIDLE_D

	12,//RIG_ENGINE_STATE_WALK_F
	12,//RIG_ENGINE_STATE_WALK_O
	12,//RIG_ENGINE_STATE_WALK_T
	12,//RIG_ENGINE_STATE_WALK_D

	12,//RIG_ENGINE_STATE_ZEN
	// HORSE
	12,//RIG_ENGINE_STATE_HORSE_ATK_FC
	12,//RIG_ENGINE_STATE_HORSE_ATK_OC
	12,//RIG_ENGINE_STATE_HORSE_ATK_TC
	12,//RIG_ENGINE_STATE_HORSE_ATK_DC
	
	14,//RIG_ENGINE_STATE_HORSE_ATK_F
	14,//RIG_ENGINE_STATE_HORSE_ATK_O
	14,//RIG_ENGINE_STATE_HORSE_ATK_T
	14,//RIG_ENGINE_STATE_HORSE_ATK_D

	6,//RIG_ENGINE_STATE_HORSE_HURT_F
	6,//RIG_ENGINE_STATE_HORSE_HURT_O
	6,//RIG_ENGINE_STATE_HORSE_HURT_T
	6,//RIG_ENGINE_STATE_HORSE_HURT_D

	12,//RIG_ENGINE_STATE_HORSE_CAST_F
	12,//RIG_ENGINE_STATE_HORSE_CAST_O
	12,//RIG_ENGINE_STATE_HORSE_CAST_T
	12,//RIG_ENGINE_STATE_HORSE_CAST_D

	10,//RIG_ENGINE_STATE_HORSE_RUN_F
	10,//RIG_ENGINE_STATE_HORSE_RUN_O
	10,//RIG_ENGINE_STATE_HORSE_RUN_T
	10,//RIG_ENGINE_STATE_HORSE_RUN_D

	12,//RIG_ENGINE_STATE_HORSE_WALK_F
	12,//RIG_ENGINE_STATE_HORSE_WALK_O
	12,//RIG_ENGINE_STATE_HORSE_WALK_T
	12,//RIG_ENGINE_STATE_HORSE_WALK_D

	14,//RIG_ENGINE_STATE_HORSE_IDLE_F
	14,//RIG_ENGINE_STATE_HORSE_IDLE_O
	14,//RIG_ENGINE_STATE_HORSE_IDLE_T
	14//RIG_ENGINE_STATE_HORSE_IDLE_D
};