#pragma once
#define JX_ANIMATION_HELM_TEXTURE_SLOT 0
#define JX_ANIMATION_CLOTH_TEXTURE_SLOT 1
#define JX_ANIMATION_HANDL_TEXTURE_SLOT 2
#define JX_ANIMATION_HANDR_TEXTURE_SLOT 3
#define JX_ANIMATION_WEAPON_PRIMARY_TEXTURE_SLOT 4
#define JX_ANIMATION_WEAPON_SECONDARY_TEXTURE_SLOT 5
#define JX_ANIMATION_HORSE_HEAD_TEXTURE_SLOT 6
#define JX_ANIMATION_HORSE_BACK_TEXTURE_SLOT 7
#define JX_ANIMATION_HORSE_TAIL_TEXTURE_SLOT 8

#define JX_ANIMATION_PATH_CHARACTER_CLOTH_M		"character_cloth_male"
#define JX_ANIMATION_PATH_CHARACTER_CLOTH_F		"character_cloth_female"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_M		"character_handl_male"
#define JX_ANIMATION_PATH_CHARACTER_HANDL_F		"character_handl_female"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_M		"character_handr_male"
#define JX_ANIMATION_PATH_CHARACTER_HANDR_F		"character_handr_female"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_M		"character_head_male"
#define JX_ANIMATION_PATH_CHARACTER_HEAD_F		"character_head_female"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_M		"character_cape_male"
#define JX_ANIMATION_PATH_CHARACTER_CAPE_F		"character_cape_female"
#define JX_ANIMATION_PATH_WEAPON_LIGHT_M		"weapon_light_male"
#define JX_ANIMATION_PATH_WEAPON_LIGHT_F		"weapon_light_female"
#define JX_ANIMATION_PATH_WEAPON_HEAVY_M		"weapon_heavy_male"
#define JX_ANIMATION_PATH_WEAPON_HEAVY_F		"weapon_heavy_female"
#define JX_ANIMATION_PATH_WEAPON_DUALL_M		"weapon_duall_male"
#define JX_ANIMATION_PATH_WEAPON_DUALL_F		"weapon_duall_female"
#define JX_ANIMATION_PATH_WEAPON_DUALR_M		"weapon_dualr_male"
#define JX_ANIMATION_PATH_WEAPON_DUALR_F		"weapon_dualr_female"
#define JX_ANIMATION_PATH_RIDE_HEAD				"horse_head"
#define JX_ANIMATION_PATH_RIDE_BACK				"horse_back"
#define JX_ANIMATION_PATH_RIDE_TAIL				"horse_tail"

enum JX_GENDER
{
	JX_GENDER_MALE = 1,
	JX_GENDER_FEMALE = 0,
};
enum JX_DIRECTION
{
	JX_DIRECTION_DOWN			= 0,
	JX_DIRECTION_LOWER_RIGHT	= 1,
	JX_DIRECTION_RIGHT			= 2,
	JX_DIRECTION_UPPER_RIGHT	= 3,
	JX_DIRECTION_UP				= 4,
	JX_DIRECTION_UPPER_LEFT		= 5,
	JX_DIRECTION_LEFT			= 6,
	JX_DIRECTION_LOWER_LEFT		= 7,

};
/*
-------------------------------------------------------------------------------------------------------------------------
WARNING:	below are bit operation, it's hard to understand.
if you wanna hack them, bring pen and paper, write down the value in bit to find out the rule of notation.
-------------------------------------------------------------------------------------------------------------------------
*/
#define JX_HORSE_BIT_OFFSET 6
#define JX_VOID_HORSE_FLAG 0x3F// 00111111
#define JX_KEEP_HORSE_FLAG 0xC0// 11000000
enum JX_HORSE_STATE
{
	JX_HORSE_STATE_ENABLE				= 1,
	JX_HORSE_STATE_DISABLE				= 0,
};
#define JX_WEAPON_BIT_OFFSET 4
#define JX_VOID_WEAPON_FLAG 0xCF// 11001111
#define JX_KEEP_WEAPON_FLAG 0x30// 00110000
enum JX_WEAPON_STATE
{
	JX_WEAPON_STATE_FREE				= 0,
	JX_WEAPON_STATE_LIGHT				= 1,
	JX_WEAPON_STATE_HEAVY				= 2,
	JX_WEAPON_STATE_DUAL				= 3,
};
#define JX_ACTION_BIT_OFFSET 0
#define JX_VOID_ACTION_FLAG 0xF0// 11110000
#define JX_KEEP_ACTION_FLAG 0x0F// 00001111
enum JX_ACTION_STATE
{
	JX_ACTION_STATE_ZEN					= 0,
	JX_ACTION_STATE_IDLE				= 1,
	JX_ACTION_STATE_READY				= 2,
	JX_ACTION_STATE_WALK				= 3,
	JX_ACTION_STATE_RUN					= 4,
	JX_ACTION_STATE_JUMP				= 5,
	JX_ACTION_STATE_ATKCRIT				= 6,
	JX_ACTION_STATE_ATK					= 7,
	JX_ACTION_STATE_CAST				= 8,
	JX_ACTION_STATE_HURT				= 9,
	JX_ACTION_STATE_FALL				= 10,
};
enum JX_ANIMATION_STATE
{
	JX_ANIMATION_STATE_ZEN				= 0 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),

	JX_ANIMATION_STATE_IDLE_FREE		= 1 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_READY_FREE		= 2 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_WALK_FREE		= 3 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RUN_FREE			= 4 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_JUMP				= 5 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATKCRIT_FREE		= 6 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATK_FREE			= 7 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_CAST_FREE		= 8 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_HURT_FREE		= 9 | (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_FALL_FREE		= 10| (0 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),

	JX_ANIMATION_STATE_IDLE_LIGHT		= 1 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_READY_LIGHT		= 2 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_WALK_LIGHT		= 3 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RUN_LIGHT		= 4 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATKCRIT_LIGHT	= 6 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATK_LIGHT		= 7 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_CAST_LIGHT		= 8 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_HURT_LIGHT		= 9 | (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_FALL_LIGHT		= 10| (1 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),

	JX_ANIMATION_STATE_IDLE_HEAVY		= 1 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_READY_HEAVY		= 2 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_WALK_HEAVY		= 3 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RUN_HEAVY		= 4 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATKCRIT_HEAVY	= 6 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATK_HEAVY		= 7 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_CAST_HEAVY		= 8 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_HURT_HEAVY		= 9 | (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_FALL_HEAVY		= 10| (2 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),

	JX_ANIMATION_STATE_IDLE_DUAL		= 1 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_READY_DUAL		= 2 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_WALK_DUAL		= 3 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RUN_DUAL			= 4 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATKCRIT_DUAL		= 6 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_ATK_DUAL			= 7 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_CAST_DUAL		= 8 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_HURT_DUAL		= 9 | (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_FALL_DUAL		= 10| (3 << JX_WEAPON_BIT_OFFSET) | (0 << JX_HORSE_BIT_OFFSET),

	// RIDE
	JX_ANIMATION_STATE_RIDE_IDLE		= 1 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_WALK		= 3 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_RUN			= 4 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_ATKCRIT		= 6 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_ATK			= 7 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_CAST		= 8 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_HURT		= 9 | (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
	JX_ANIMATION_STATE_RIDE_FALL		= 10| (0 << JX_WEAPON_BIT_OFFSET) | (1 << JX_HORSE_BIT_OFFSET),
};
#define JX_ANIMATION_STATE_MAX 75
/*
-------------------------------------------------------------------------------------------------------------------------
WARNING:	bit operation ended
-------------------------------------------------------------------------------------------------------------------------
*/
const unsigned char JX_ANIMATION_MALE_FRAME[JX_ANIMATION_STATE_MAX] = {
	9,//JX_ANIMATION_STATE_ZEN

	15,//JX_ANIMATION_STATE_IDLE_FREE
	11,//JX_ANIMATION_STATE_READY_FREE
	15,//JX_ANIMATION_STATE_WALK_FREE
	11,//JX_ANIMATION_STATE_RUN_FREE
	20,//JX_ANIMATION_STATE_JUMP
	16,//JX_ANIMATION_STATE_ATKCRIT_FREE
	18,//JX_ANIMATION_STATE_ATK_FREE
	12,//JX_ANIMATION_STATE_CAST_FREE
	9,//JX_ANIMATION_STATE_HURT_FREE
	12,//JX_ANIMATION_STATE_FALL_FREE
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_LIGHT
	11,//JX_ANIMATION_STATE_READY_LIGHT
	15,//JX_ANIMATION_STATE_WALK_LIGHT
	11,//JX_ANIMATION_STATE_RUN_LIGHT
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_LIGHT
	14,//JX_ANIMATION_STATE_ATK_LIGHT
	12,//JX_ANIMATION_STATE_CAST_LIGHT
	8,//JX_ANIMATION_STATE_HURT_LIGHT
	11,//JX_ANIMATION_STATE_FALL_LIGHT
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_HEAVY
	11,//JX_ANIMATION_STATE_READY_HEAVY
	15,//JX_ANIMATION_STATE_WALK_HEAVY
	11,//JX_ANIMATION_STATE_RUN_HEAVY
	0,
	12,//JX_ANIMATION_STATE_ATKCRIT_HEAVY
	12,//JX_ANIMATION_STATE_ATK_HEAVY
	13,//JX_ANIMATION_STATE_CAST_HEAVY
	7,//JX_ANIMATION_STATE_HURT_HEAVY
	15,//JX_ANIMATION_STATE_FALL_HEAVY
	0,
	0,
	0,
	0,
	0,
	0,
	15,//JX_ANIMATION_STATE_IDLE_DUAL
	11,//JX_ANIMATION_STATE_READY_DUAL
	15,//JX_ANIMATION_STATE_WALK_DUAL
	11,//JX_ANIMATION_STATE_RUN_DUAL
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_DUAL
	12,//JX_ANIMATION_STATE_ATK_DUAL
	16,//JX_ANIMATION_STATE_CAST_DUAL
	12,//JX_ANIMATION_STATE_HURT_DUAL
	18,//JX_ANIMATION_STATE_FALL_DUAL
	0,
	0,
	0,
	0,
	0,
	0,
	// RIDE
	14,//JX_ANIMATION_STATE_RIDE_IDLE_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_WALK_FREE
	10,//JX_ANIMATION_STATE_RIDE_RUN_FREE
	0,
	14,//JX_ANIMATION_STATE_RIDE_ATKCRIT_FREE
	12,//JX_ANIMATION_STATE_RIDE_ATK_FREE
	12,//JX_ANIMATION_STATE_RIDE_CAST_FREE
	6,//JX_ANIMATION_STATE_RIDE_HURT_FREE
	14,//JX_ANIMATION_STATE_RIDE_FALL_FREE
};
const unsigned char JX_ANIMATION_FEMALE_FRAME[JX_ANIMATION_STATE_MAX] = {
	12,//JX_ANIMATION_STATE_ZEN
	10,//JX_ANIMATION_STATE_IDLE_FREE
	8,//JX_ANIMATION_STATE_READY_FREE
	12,//JX_ANIMATION_STATE_WALK_FREE
	12,//JX_ANIMATION_STATE_RUN_FREE
	14,//JX_ANIMATION_STATE_JUMP
	12,//JX_ANIMATION_STATE_ATKCRIT_FREE
	12,//JX_ANIMATION_STATE_ATK_FREE
	12,//JX_ANIMATION_STATE_CAST_FREE
	8,//JX_ANIMATION_STATE_HURT_FREE
	13,//JX_ANIMATION_STATE_FALL_FREE
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_LIGHT
	12,//JX_ANIMATION_STATE_READY_LIGHT
	12,//JX_ANIMATION_STATE_WALK_LIGHT
	12,//JX_ANIMATION_STATE_RUN_LIGHT
	0,
	13,//JX_ANIMATION_STATE_ATKCRIT_LIGHT
	13,//JX_ANIMATION_STATE_ATK_LIGHT
	10,//JX_ANIMATION_STATE_CAST_LIGHT
	8,//JX_ANIMATION_STATE_HURT_LIGHT
	15,//JX_ANIMATION_STATE_FALL_LIGHT
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_HEAVY
	8,//JX_ANIMATION_STATE_READY_HEAVY
	12,//JX_ANIMATION_STATE_WALK_HEAVY
	12,//JX_ANIMATION_STATE_RUN_HEAVY
	0,
	13,//JX_ANIMATION_STATE_ATKCRIT_HEAVY
	12,//JX_ANIMATION_STATE_ATK_HEAVY
	12,//JX_ANIMATION_STATE_CAST_HEAVY
	6,//JX_ANIMATION_STATE_HURT_HEAVY
	10,//JX_ANIMATION_STATE_FALL_HEAVY
	0,
	0,
	0,
	0,
	0,
	0,
	8,//JX_ANIMATION_STATE_IDLE_DUAL
	8,//JX_ANIMATION_STATE_READY_DUAL
	12,//JX_ANIMATION_STATE_WALK_DUAL
	12,//JX_ANIMATION_STATE_RUN_DUAL
	0,
	16,//JX_ANIMATION_STATE_ATKCRIT_DUAL
	12,//JX_ANIMATION_STATE_ATK_DUAL
	10,//JX_ANIMATION_STATE_CAST_DUAL
	6,//JX_ANIMATION_STATE_HURT_DUAL
	10,//JX_ANIMATION_STATE_FALL_DUAL
	0,
	0,
	0,
	0,
	0,
	0,
	// RIDE
	14,//JX_ANIMATION_STATE_RIDE_IDLE_FREE
	0,
	12,//JX_ANIMATION_STATE_RIDE_WALK_FREE
	10,//JX_ANIMATION_STATE_RIDE_RUN_FREE
	0,
	14,//JX_ANIMATION_STATE_RIDE_ATK_FREEC
	12,//JX_ANIMATION_STATE_RIDE_ATK_FREE
	12,//JX_ANIMATION_STATE_RIDE_CAST_FREE
	6,//JX_ANIMATION_STATE_RIDE_HURT_FREE
	14,//JX_ANIMATION_STATE_RIDE_FALL_FREE
};

const unsigned char JX_ANIMATION_COMBO_RENDER_ORDER[8][9] = 
{
	// helm, cloth, handl, handr, weapon_primary(left), weapon_secondary(right), horse_head, horse_back, horse_tail
	// render order 9 = force disable render
	{7, 2, 5, 3, 6, 4, 8, 1, 0},// DOWN
	{5, 4, 3, 7, 2, 8, 6, 1, 0},// LOWER RIGHT
	{5, 4, 3, 7, 2, 8, 6, 1, 0},// RIGHT
	{5, 4, 3, 7, 2, 8, 6, 1, 0},// UPPER RIGHT
	{2, 3, 5, 8, 6, 7, 0, 1, 4},// UP
	{6, 5, 7, 3, 8, 2, 4, 1, 0},// UPPER LEFT
	{6, 5, 7, 3, 8, 2, 4, 1, 0},// LEFT
	{6, 5, 7, 3, 8, 2, 4, 1, 0},// LOWER LEFT
};